### ISSUE TITLE
URL to not existing webpage

### ISSUE THREAD

**Issue by selimerunkut** [across-protocol/across.to#51]
Reproduce BUG:

1) Go to https://risklabs.foundation/#our-projects
2) Click BRAND ASSETS
3) see missing page https://docs.across.to/additional-info/brand-assets

<img width="1192" alt="Screenshot 2024-07-28 at 16 29 27" src="https://github.com/user-attachments/assets/371eb0ba-460d-4ac6-9ad7-b04472accc73">

**Comment by james-a-morris** [comment]
Tracking the fix internally. Thanks for the callout!
